version: '3'
services:
  anand-app:
  # image: ${docker-registry}/my-app:1.0
    build: .
    ports:
      - 3000:3000
    networks: 
      - mongo-compose-network
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks: 
        - mongo-compose-network
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks: 
        - mongo-compose-network
    depends_on:
      - mongodb
volumes:
  mongo-data:
    driver: local
networks:
  mongo-compose-network:
    driver: bridge